Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP2','Options','Answer',0);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP3','Options','Answer',1);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP4','Options','Answer',1);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP5','Options','Answer',1);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP6','Options','Answer',0);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP7','Options','Answer',1);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP8','Options','Answer',1);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP9','Options','Answer',0);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP10','Options','Answer',1);
Insert Into P_PREGUNTA_RESPUESTA (ID_QUIZZ,ID_PREGUNTA,OPCIONES,RESPUESTA,CORRECTA) Values
('QZZ2','QZP11','Options','Answer',1);
Select * From p_pregunta_respuesta
