Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('VHF2','MATEMATICAS',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('SLR4','ESPAÑOL',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('SLR4','BASE DE DATOS',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('SLR4','PROGRAMACION',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('SLR4','INGLES',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('DCG10','FRANCES',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('DCG10','CALCULO',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('DCG10','HISTORIA',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('DCG10','METODOLOGIA',Default,'Default');
Insert Into P_QUIZZ (ID_USUARIO,TITULO,FECHA_CREACION,DESCRIPCION_QUIZZ)Values
('DCG10','ETICA',Default,'Default');
Select * From P_usuario
Select * From p_quizz
Select * From P_QUIZZ_PREGUNTA Where id_quizz = 'QZZ2'
