Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR2','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR3','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR4','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR5','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR6','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR7','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR8','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR9','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR10','Answer');
Insert Into P_USUARIO_RESPUESTAS (ID_USUARIO_QUIZZ,ID_RESPUESTA,RESPUESTA_USUARIO) Values
('UQZ2','PRR11','Answer');

Select * From P_USUARIO_RESPUESTAS
